namespace Service;

public class Helper
{
    static Helper()
    {
        string envVarKeyName = "pgconn";
        
        
    }
    
    
    
    public static string RebuildScript = @"
DROP SCHEMA IF EXISTS news CASCADE;
CREATE SCHEMA news;
create table if not exists news.articles
(
    boxid       integer generated by default as identity,
    name        text,
    size            text,
    description          text,
    price         FLOAT,        
    boximgurl text,
    constraint boxpk
        primary key (boxid)
);
 ";
}